package tablas;
// Generated 07-jul-2017 12:51:10 by Hibernate Tools 5.2.3.Final

/**
 * Administradores generated by hbm2java
 */
public class Administradores implements java.io.Serializable {

	private AdministradoresId id;
	private Usuarios usuarios;

	public Administradores() {
	}

	public Administradores(AdministradoresId id, Usuarios usuarios) {
		this.id = id;
		this.usuarios = usuarios;
	}

	public AdministradoresId getId() {
		return this.id;
	}

	public void setId(AdministradoresId id) {
		this.id = id;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

}
