package tablas;
// Generated 07-jul-2017 12:51:10 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * AdministradoresId generated by hbm2java
 */
public class AdministradoresId implements java.io.Serializable {

	private String dni;
	private String nombre;
	private Date fechaDeEntrada;

	public AdministradoresId() {
	}

	public AdministradoresId(String dni) {
		this.dni = dni;
	}

	public AdministradoresId(String dni, String nombre, Date fechaDeEntrada) {
		this.dni = dni;
		this.nombre = nombre;
		this.fechaDeEntrada = fechaDeEntrada;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaDeEntrada() {
		return this.fechaDeEntrada;
	}

	public void setFechaDeEntrada(Date fechaDeEntrada) {
		this.fechaDeEntrada = fechaDeEntrada;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdministradoresId))
			return false;
		AdministradoresId castOther = (AdministradoresId) other;

		return ((this.getDni() == castOther.getDni())
				|| (this.getDni() != null && castOther.getDni() != null && this.getDni().equals(castOther.getDni())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getFechaDeEntrada() == castOther.getFechaDeEntrada())
						|| (this.getFechaDeEntrada() != null && castOther.getFechaDeEntrada() != null
								&& this.getFechaDeEntrada().equals(castOther.getFechaDeEntrada())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDni() == null ? 0 : this.getDni().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getFechaDeEntrada() == null ? 0 : this.getFechaDeEntrada().hashCode());
		return result;
	}

}
