package tablas;
// Generated 07-jul-2017 12:51:10 by Hibernate Tools 5.2.3.Final

/**
 * MovimientosId generated by hbm2java
 */
public class MovimientosId implements java.io.Serializable {

	private String movimiento;
	private Integer id;
	private String operacion;
	private String fecha;
	private String hora;
	private String consultaRealizada;

	public MovimientosId() {
	}

	public MovimientosId(String movimiento, Integer id, String operacion, String fecha, String hora,
			String consultaRealizada) {
		this.movimiento = movimiento;
		this.id = id;
		this.operacion = operacion;
		this.fecha = fecha;
		this.hora = hora;
		this.consultaRealizada = consultaRealizada;
	}

	public String getMovimiento() {
		return this.movimiento;
	}

	public void setMovimiento(String movimiento) {
		this.movimiento = movimiento;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOperacion() {
		return this.operacion;
	}

	public void setOperacion(String operacion) {
		this.operacion = operacion;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	public String getConsultaRealizada() {
		return this.consultaRealizada;
	}

	public void setConsultaRealizada(String consultaRealizada) {
		this.consultaRealizada = consultaRealizada;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MovimientosId))
			return false;
		MovimientosId castOther = (MovimientosId) other;

		return ((this.getMovimiento() == castOther.getMovimiento()) || (this.getMovimiento() != null
				&& castOther.getMovimiento() != null && this.getMovimiento().equals(castOther.getMovimiento())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getOperacion() == castOther.getOperacion()) || (this.getOperacion() != null
						&& castOther.getOperacion() != null && this.getOperacion().equals(castOther.getOperacion())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null && castOther.getHora() != null
						&& this.getHora().equals(castOther.getHora())))
				&& ((this.getConsultaRealizada() == castOther.getConsultaRealizada())
						|| (this.getConsultaRealizada() != null && castOther.getConsultaRealizada() != null
								&& this.getConsultaRealizada().equals(castOther.getConsultaRealizada())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMovimiento() == null ? 0 : this.getMovimiento().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getOperacion() == null ? 0 : this.getOperacion().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37 * result + (getConsultaRealizada() == null ? 0 : this.getConsultaRealizada().hashCode());
		return result;
	}

}
