package tablas;
// Generated 07-jul-2017 12:51:10 by Hibernate Tools 5.2.3.Final

/**
 * Movimientos generated by hbm2java
 */
public class Movimientos implements java.io.Serializable {

	private MovimientosId id;

	public Movimientos() {
	}

	public Movimientos(MovimientosId id) {
		this.id = id;
	}

	public MovimientosId getId() {
		return this.id;
	}

	public void setId(MovimientosId id) {
		this.id = id;
	}

}
