package tablas;
// Generated 07-jul-2017 12:51:10 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="Usuarios")
public class Usuarios implements java.io.Serializable {

	@Id
	@Column(name="dni")
	private String dni;
	
	@Column(name="name")
	private String name;
	
	@Column(name="pass")
	private String pass;
	
	@Column(name="mail")
	private String mail;
	
	@Column(name="edad")
	private String edad;
	
	@Column(name="poblacion")
	private String poblacion;
	
	@Column(name="pais")
	private String pais;
	
	private Set administradoreses = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String dni) {
		this.dni = dni;
	}

	public Usuarios(String dni, String name, String pass, String mail, String edad, String poblacion, String pais,
			Set administradoreses) {
		this.dni = dni;
		this.name = name;
		this.pass = pass;
		this.mail = mail;
		this.edad = edad;
		this.poblacion = poblacion;
		this.pais = pais;
		this.administradoreses = administradoreses;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getEdad() {
		return this.edad;
	}

	public void setEdad(String edad) {
		this.edad = edad;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public Set getAdministradoreses() {
		return this.administradoreses;
	}

	public void setAdministradoreses(Set administradoreses) {
		this.administradoreses = administradoreses;
	}

}
